index:   # Je choisis le nom de ma route. /!\ Pas de doublon
  path: /   #slash/  Ma route (ici rien car oage d'acceuil
  controller: App\Controller\DefaultController::index

contact:   # Je choisis le nom de ma route. /!\ Pas de doublon
  path: /page/contact
  controller: App\Controller\DefaultController::contact